name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:

jobs:
  build:
    name: PlatformIO Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Build PlatformIO project
        run: platformio run
